CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_id INT NOT NULL,
    amount FLOAT NOT NULL,
    status VARCHAR(255) NOT NULL,
    billed_dated DATETIME NOT NULL,
    paid_dated DATETIME NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL
);
